using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using AFMediaBar.Classes.Models.Credits;
using AFMediaBar.Resources;

namespace AFMediaBar.Classes.Services.Credits;

/// <summary>
/// 一份名单的解析结果。
/// The result of parsing one name list.
/// </summary>
/// <param name="Contributors">贡献者（解析贡献者文件时有值）。/ Contributors, set when a contributors file was parsed.</param>
/// <param name="Sponsors">赞助者（解析赞助名单时有值）。/ Sponsors, set when a sponsor list was parsed.</param>
/// <param name="FailureReason">失败原因；可直接展示。/ The failure reason, ready to display.</param>
public sealed record CreditsListParseResult(
    IReadOnlyList<ContributorInfo>? Contributors,
    IReadOnlyList<SponsorInfo>? Sponsors,
    string? FailureReason)
{
    /// <summary>是否解析成功。/ Whether parsing succeeded.</summary>
    public bool Succeeded => FailureReason is null;

    /// <summary>成功时的结果。/ A successful result.</summary>
    /// <param name="contributors">贡献者。/ Contributors.</param>
    public static CreditsListParseResult FromContributors(IReadOnlyList<ContributorInfo> contributors) =>
        new(contributors, null, null);

    /// <summary>成功时的结果。/ A successful result.</summary>
    /// <param name="sponsors">赞助者。/ Sponsors.</param>
    public static CreditsListParseResult FromSponsors(IReadOnlyList<SponsorInfo> sponsors) =>
        new(null, sponsors, null);

    /// <summary>失败时的结果。/ A failed result.</summary>
    /// <param name="reason">失败原因。/ The failure reason.</param>
    public static CreditsListParseResult Failure(string reason) => new(null, null, reason);
}

/// <summary>
/// 两份名单的解析策略，以及把它们排成界面顺序的规则。
/// The parsing policy for both lists, together with the rules that order them for the interface.
///
/// 两条取舍与版本清单一致：**未知字段一律忽略**（名单可以只做追加式演进），**单条不合法只丢该条**而不是让整份名单失败
/// （一个人把名字写空不该让整页名单消失）。
/// Two decisions match the version manifest: **unknown fields are ignored**, so a list can evolve by appending, and **one invalid entry is
/// dropped on its own** rather than failing the whole list — one empty name should not make the entire list disappear.
/// </summary>
public static class CreditsJsonParser
{
    /// <summary>支持的赞助名单 schema 版本。/ The sponsor-list schema version this application understands.</summary>
    public const int SupportedSponsorsSchemaVersion = 1;

    /// <summary>界面上展示的贡献者条数上限：贡献者可能上百人，而这一页不是排行榜。/ Upper bound on contributors shown: there can be a hundred of them, and this page is not a leaderboard.</summary>
    public const int MaximumContributors = 40;

    /// <summary>界面上展示的赞助者条数上限。/ Upper bound on sponsors shown.</summary>
    public const int MaximumSponsors = 200;

    /// <summary>
    /// 解析 GitHub 贡献者接口或仓库快照的内容。
    ///
    /// 两种来源的结构刻意做成一样（快照就是接口响应原样存下来），因此这里只有一个解析器：
    /// 快照由维护者用一条命令生成，而"两份不同结构的名单"是后续一定会出错的地方。
    /// Parses the GitHub contributors API response or the repository snapshot.
    ///
    /// Both sources deliberately share one structure — the snapshot is the API response stored as-is — so there is exactly one parser here:
    /// the snapshot is generated by a single command, and "two lists with different shapes" is where things would eventually go wrong.
    /// </summary>
    /// <param name="json">JSON 文本（接口响应数组，或含 <c>contributors</c> 数组的对象）。/ JSON text: either the API's array or an object carrying a <c>contributors</c> array.</param>
    /// <returns>解析结果。/ The parse result.</returns>
    public static CreditsListParseResult ParseContributors(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.Empty"));
        }

        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(json);
        }
        catch (JsonException exception)
        {
            Debug.WriteLine($"[Credits] Contributors JSON invalid: {exception.Message}");
            return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.InvalidJson"));
        }

        using (document)
        {
            var root = document.RootElement;
            if (root.ValueKind == JsonValueKind.Object &&
                root.TryGetProperty("contributors", out var nested))
            {
                root = nested;
            }

            if (root.ValueKind != JsonValueKind.Array)
            {
                return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.ContributorsShape"));
            }

            var contributors = new List<ContributorInfo>();
            foreach (var element in root.EnumerateArray())
            {
                if (ParseContributor(element) is { } contributor)
                {
                    contributors.Add(contributor);
                }
            }

            return contributors.Count == 0
                ? CreditsListParseResult.Failure(Translations.Get("Credits.Reason.ContributorsEmpty"))
                : CreditsListParseResult.FromContributors(OrderContributors(contributors));
        }
    }

    /// <summary>
    /// 解析仓库里的赞助名单。
    /// Parses the sponsor list in the repository.
    /// </summary>
    /// <param name="json">JSON 文本。/ JSON text.</param>
    /// <returns>解析结果。/ The parse result.</returns>
    public static CreditsListParseResult ParseSponsors(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.Empty"));
        }

        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(json);
        }
        catch (JsonException exception)
        {
            Debug.WriteLine($"[Credits] Sponsors JSON invalid: {exception.Message}");
            return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.InvalidJson"));
        }

        using (document)
        {
            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.SponsorsShape"));
            }

            if (root.TryGetProperty("schemaVersion", out var schemaElement) &&
                schemaElement.ValueKind == JsonValueKind.Number &&
                schemaElement.TryGetInt32(out var schemaVersion) &&
                schemaVersion > SupportedSponsorsSchemaVersion)
            {
                return CreditsListParseResult.Failure(
                    Translations.Format("Credits.Reason.SchemaTooNew", schemaVersion, SupportedSponsorsSchemaVersion));
            }

            if (!root.TryGetProperty("sponsors", out var sponsorsElement) ||
                sponsorsElement.ValueKind != JsonValueKind.Array)
            {
                return CreditsListParseResult.Failure(Translations.Get("Credits.Reason.SponsorsShape"));
            }

            var sponsors = new List<SponsorInfo>();
            foreach (var element in sponsorsElement.EnumerateArray())
            {
                if (ParseSponsor(element) is { } sponsor)
                {
                    sponsors.Add(sponsor);
                }
            }

            // 名单合法但没有条目是**正常状态**（还没有赞助者），因此返回成功加空列表，而不是失败：
            // 页面据此显示"暂无"，而不是"加载失败"。
            // A valid list without entries is a **normal state** — nobody has sponsored yet — so this succeeds with an empty list rather than
            // failing; the page then says "none yet" instead of "failed to load".
            return CreditsListParseResult.FromSponsors(OrderSponsors(sponsors));
        }
    }

    /// <summary>
    /// 把贡献者排成展示顺序：提交次数从多到少，同次数按用户名不区分大小写排序。
    /// Orders contributors for display: most contributions first, ties broken by login, case-insensitively.
    /// </summary>
    /// <param name="contributors">贡献者。/ Contributors.</param>
    /// <returns>排序并截断后的列表。/ The ordered and truncated list.</returns>
    public static IReadOnlyList<ContributorInfo> OrderContributors(IEnumerable<ContributorInfo> contributors) =>
        contributors
            .Where(contributor => !string.IsNullOrWhiteSpace(contributor.Login))
            .OrderByDescending(contributor => contributor.Contributions)
            .ThenBy(contributor => contributor.Login, StringComparer.OrdinalIgnoreCase)
            .Take(MaximumContributors)
            .ToArray();

    /// <summary>
    /// 把赞助者排成展示顺序：先按档位（<c>gold</c> → <c>silver</c> → <c>bronze</c> → 其它 → <c>backer</c>），同档位按名称。
    ///
    /// 档位顺序固定写在这里：名单文件只写档位标识，排序规则属于界面，因此换写法（例如新增一档）时改一处即可。
    /// Orders sponsors for display: by tier (<c>gold</c> → <c>silver</c> → <c>bronze</c> → anything else → <c>backer</c>), then by name.
    ///
    /// The tier order is fixed here: the list file only carries a tier identifier, and ordering is an interface concern, so adding a tier is a
    /// one-line change.
    /// </summary>
    /// <param name="sponsors">赞助者。/ Sponsors.</param>
    /// <returns>排序并截断后的列表。/ The ordered and truncated list.</returns>
    public static IReadOnlyList<SponsorInfo> OrderSponsors(IEnumerable<SponsorInfo> sponsors) =>
        sponsors
            .Where(sponsor => !string.IsNullOrWhiteSpace(sponsor.Name))
            .OrderBy(sponsor => TierRank(sponsor.Tier))
            .ThenBy(sponsor => sponsor.Name, StringComparer.OrdinalIgnoreCase)
            .Take(MaximumSponsors)
            .ToArray();

    /// <summary>档位在展示顺序里的名次（越小越靠前）。/ A tier's rank in the display order, smaller meaning earlier.</summary>
    /// <param name="tier">档位标识。/ Tier identifier.</param>
    /// <returns>名次。/ The rank.</returns>
    public static int TierRank(string? tier) => tier?.Trim().ToLowerInvariant() switch
    {
        "gold" => 0,
        "silver" => 1,
        "bronze" => 2,
        null or "" => 4,
        "backer" => 5,
        _ => 3
    };

    private static ContributorInfo? ParseContributor(JsonElement element)
    {
        if (element.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        var login = ReadString(element, "login");
        if (string.IsNullOrWhiteSpace(login))
        {
            return null;
        }

        var profileUrl = ReadString(element, "html_url");
        if (string.IsNullOrWhiteSpace(profileUrl))
        {
            profileUrl = $"https://github.com/{login}";
        }

        return new ContributorInfo(
            login.Trim(),
            ReadInt(element, "contributions"),
            profileUrl.Trim(),
            ReadString(element, "avatar_url")?.Trim());
    }

    private static SponsorInfo? ParseSponsor(JsonElement element)
    {
        if (element.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        var name = ReadString(element, "name");
        if (string.IsNullOrWhiteSpace(name))
        {
            return null;
        }

        return new SponsorInfo(
            name.Trim(),
            ReadString(element, "tier")?.Trim() ?? string.Empty,
            ReadString(element, "note")?.Trim(),
            ReadString(element, "url")?.Trim(),
            ReadString(element, "since")?.Trim());
    }

    private static string? ReadString(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString()
            : null;

    private static int ReadInt(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var value) &&
        value.ValueKind == JsonValueKind.Number &&
        value.TryGetInt32(out var number)
            ? number
            : 0;

    /// <summary>把数字按不变文化格式化，只用于诊断。/ Formats a number with the invariant culture, for diagnostics only.</summary>
    /// <param name="value">数值。/ The value.</param>
    /// <returns>文本。/ Text.</returns>
    internal static string Describe(int value) => value.ToString(CultureInfo.InvariantCulture);
}
